fruits = ["pineapple", "mango", "papaya", "grapes"]
print(fruits)
print(fruits[0])
print(fruits[-1])
fruits.append("banana")     
fruits.insert(2,"apple")   
fruits.extend(["guvava","kiwi"]) 
print(fruits)
fruits.pop(2)  
print(fruits)   
fruits.remove("mango")  
print(fruits)     
del fruits[1:3]
print(fruits)   
fruits.sort()
print(fruits)     
fruits.reverse() 
print(fruits)     
fruits.clear()     
print(fruits)